/// <reference path="../pb_data/types.d.ts" />

// Generated by ph create — enables the selected auth methods on the users
// collection. OAuth2 providers are configured separately in pb_hooks/oauth.pb.js.
migrate(
  (app) => {
    const users = app.findCollectionByNameOrId('users')
    users.passwordAuth.enabled = false
    users.otp.enabled = false
    users.mfa.enabled = false
    app.save(users)
  },
  (app) => {
    const users = app.findCollectionByNameOrId('users')
    users.passwordAuth.enabled = true
    users.otp.enabled = false
    users.mfa.enabled = false
    app.save(users)
  },
)
