/// <reference path="../pb_data/types.d.ts" />

// Generated by ph create — syncs OAuth2 providers from environment secrets on
// every startup. Add <PROVIDER>_CLIENT_ID / <PROVIDER>_CLIENT_SECRET in the
// PocketHost dashboard (Secrets) and restart the instance to activate.
onBootstrap((e) => {
  e.next()

  const wanted = [
    {
      name: 'google',
      idVar: 'GOOGLE_CLIENT_ID',
      secretVar: 'GOOGLE_CLIENT_SECRET',
    },
    {
      name: 'github',
      idVar: 'GITHUB_CLIENT_ID',
      secretVar: 'GITHUB_CLIENT_SECRET',
    },
  ]

  const users = e.app.findCollectionByNameOrId('users')
  const providers = []
  for (const entry of wanted) {
    const clientId = $os.getenv(entry.idVar)
    const clientSecret = $os.getenv(entry.secretVar)
    if (clientId && clientSecret) {
      providers.push({
        name: entry.name,
        clientId: clientId,
        clientSecret: clientSecret,
      })
    } else {
      console.log(
        '[oauth] ' +
          entry.name +
          ' not configured — set ' +
          entry.idVar +
          ' and ' +
          entry.secretVar +
          ' in PocketHost secrets',
      )
    }
  }

  users.oauth2.enabled = providers.length > 0
  users.oauth2.providers = providers
  e.app.save(users)
})
